source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

platform :ios, '13.0'

target 'v2ray' do
  
end

target 'Tunnel' do
  
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
